import type { Metadata } from "next";
import { Great_Vibes, Parisienne, Cinzel, Poppins } from "next/font/google";
import "./globals.css";

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  variable: "--font-great-vibes",
  display: "swap",
  weight: ["400"],
});
const parsienne = Parisienne({
  subsets: ["latin"],
  variable: "--font-parisienne",
  display: "swap",
  weight: ["400"],
});
const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-great-vibes",
  display: "swap",
  weight: ["400","500","600","700","800"],
});
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: ["400","500","600","700","800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${greatVibes.variable} ${parsienne.variable} ${cinzel.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
